apiVersion: apps/v1
kind: Deployment
metadata:
  name: speckle-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: speckle-frontend
    project: speckle-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speckle-frontend
      project: speckle-server
  template:
    metadata:
      labels:
        app: speckle-frontend
        project: speckle-server
    spec:
      containers:
      - name: main
        image: speckle/speckle-frontend:v{{ .Chart.AppVersion }}
